apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-bot
  namespace: {{ .Values.namespace }}
  labels:
    app: bot
spec:
  replicas: {{ .Values.bot.replicas }}
  selector:
    matchLabels:
      app: bot
  template:
    metadata:
      labels:
        app: bot
    spec:
      containers:
        - name: bot
          image: "{{ .Values.bot.image.repository }}:{{ .Values.bot.image.tag }}"
          imagePullPolicy: {{ .Values.bot.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.bot.port }}
