apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-dbgo
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: dbgo
  ports:
    - protocol: TCP
      port: {{ .Values.dbgo.service.port }}
      targetPort: {{ .Values.dbgo.port }}
