apiVersion: v1
kind: Service
metadata:
  name: kafka-external
  namespace: {{ .Values.kafka.namespace }}
spec:
  type: NodePort
  ports:
    - port: 9092
      nodePort: {{ .Values.kafka.nodePort }}
      name: plaintext
  selector:
    app: kafka
