apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-spam-bot
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: spam-bot
  ports:
    - protocol: TCP
      port: {{ .Values.spam_bot.service.port }}
      targetPort: {{ .Values.spam_bot.port }}
