apiVersion: apps/v1
kind: Deployment
metadata:
  name: dbgo
  namespace: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dbgo
  template:
    metadata:
      labels:
        app: dbgo
    spec:
      containers:
        - name: dbgo
          image: dbgo:latest 
          imagePullPolicy: Never  
          ports:
            - containerPort: 8080
