apiVersion: apps/v1
kind: Deployment
metadata:
  name: telegram-bot
  namespace: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: telegram-bot
  template:
    metadata:
      labels:
        app: telegram-bot
    spec:
      containers:
        - name: bot
          image: telegram-bot:latest
          imagePullPolicy: Never
          env:
            - name: API_URL
              value: "http://parser.kafka.svc.cluster.local:8000/parse"
